version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb:inception
    container_name: mariadb
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    restart: unless-stopped
    expose:
      - "3306"

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress:inception
    container_name: wordpress
    env_file:
      - .env
    environment:
      MYSQL_HOST: mariadb:3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - wordpress_data:/var/www/html/wordpress
    networks:
      - inception_network
    depends_on:
      - mariadb
    restart: unless-stopped
    expose:
      - "9000"

  nginx:
    build: ./requirements/nginx/
    image: nginx:inception
    container_name: nginx
    env_file:
      - .env
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - wordpress_data:/var/www/html/wordpress
    networks:
      - inception_network
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: unless-stopped

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/shmoreno/data/wordpress

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/shmoreno/data/mariadb

networks:
  inception_network:
    driver: bridge
